apiVersion: inv.sdcio.dev/v1alpha1
kind: TargetConnectionProfile
metadata:
  name: netconf
  namespace: default
spec:
  port: 830
  protocol: netconf
  encoding: UNKNOWN
  skipVerify: true
  includeNS: true
  operationWithNS: true
